// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://vpfnaxtmddzxhswfxdvn.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZm5heHRtZGR6eGhzd2Z4ZHZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTMxMTcsImV4cCI6MjA3Mzk2OTExN30.rbw2Hlw-ASMOZyQAp19MVruwAsYifIddm-F0Ta4XTqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'vidhya-disha-web'
    }
  }
});